export const SHOW_LIST_VIEW = 'SHOW_LIST_VIEW'
export const HIDE_LIST_VIEW = 'HIDE_LIST_VIEW'
export const FETCH_SUGGESTION_SUCCESS = 'FETCH_SUGGESTION_SUCCESS'
export const UPDATE_COORD_ORIGIN_LAT = 'UPDATE_COORD_ORIGIN_LAT'
export const UPDATE_COORD_ORIGIN_LONG = 'UPDATE_COORD_ORIGIN_LONG'
export const UPDATE_COORD_DESTINATION_LAT = 'UPDATE_COORD_DESTINATION_LAT'
export const UPDATE_COORD_DESTINATION_LONG = 'UPDATE_COORD_DESTINATION_LONG'
export const FETCH_DIRECTIONS_SUCCESS = 'FETCH_DIRECTIONS_SUCCESS'
export const FETCH_SUGGESTION = 'FETCH_SUGGESTION'
export const REQUEST_SUGGEST = 'REQUEST_SUGGEST'
export const SUCCESS_SUGGEST = 'SUCCESS_SUGGEST'
export const UPDATE_INPUT_FIELD = {
    ORIGIN: 'ORIGIN',
    DESTINATION: 'DESTINATION'
}